app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pwa.urls")),
    path("receipt/", include("receipts.urls")),
    path("", include("inspections.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/inspections/urls.py
from django.urls import path

from .views import (
    DefectCreateView,
    DefectDetailView,
    DefectListView,
    DefectUpdateView,
    InspectionApplicationCreateView,
    InspectionApplicationDetailView,
    InspectionApplicationListView,
    InspectionApplicationUpdateView,
    OfficerCreateView,
    OfficerDetailView,
    OfficerListView,
    OfficerUpdateView,
)

urlpatterns = [
    path(
        "",
        InspectionApplicationListView.as_view(),
        name="inspection-application-list",
    ),
    path(
        "inspection-application/detail/<int:pk>/",
        InspectionApplicationDetailView.as_view(),
        name="inspection-application-detail",
    ),
    path(
        "inspection-application/update/<int:pk>/",
        InspectionApplicationUpdateView.as_view(),
        name="inspection-application-update",
    ),
    path(
        "inspection-application/create/",
        InspectionApplicationCreateView.as_view(),
        name="inspection-application-create",
    ),
    #
    path("defects", DefectListView.as_view(), name="defect-list"),
    path("detail/<int:pk>/", DefectDetailView.as_view(), name="defect-detail"),
    path("create/", DefectCreateView.as_view(), name="defect-create"),
    path("update/<int:pk>/", DefectUpdateView.as_view(), name="defect-update"),
    #
    path("officers/", OfficerListView.as_view(), name="officer-list"),
    path(
        "officer/detail/<int:pk>/",
        OfficerDetailView.as_view(),
        name="officer-detail",
    ),
    path(
        "officer/update/<int:pk>/",
        OfficerUpdateView.as_view(),
        name="officer-update",
    ),
    path("officer/create/", OfficerCreateView.as_view(), name="officer-create"),
]

app/inspections/models.py
from django.db import models
from django.urls import reverse


class Location(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("location-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.name.upper()}"


class Post(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("post-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.name.upper()}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Officer(models.Model):
    name = models.CharField(max_length=100)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="posts", null=True, blank=True
    )
    licence_no = models.CharField(max_length=100, null=True, blank=True)
    office = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        related_name="offices",
        null=True,
        blank=True,
    )
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    photo = models.FileField(upload_to="electrical/photo/", null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    signature = models.FileField(
        upload_to="electrical/signature/", null=True, blank=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank=True
    )
    i_date = models.DateField(verbose_name="Issued Date", null=True, blank=True)
    ex_date = models.DateField(verbose_name="Expired Date", null=True, blank=True)
    notes = models.TextField(blank=True, null=True)
    stamp = models.FileField(upload_to="electrical/stamp/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("officer-detail", kwargs={"pk": self.pk})

    def __str__(self):
        if self.licence_no:
            return f"{self.name.title()}({self.licence_no.upper()})"
        return f"{self.name.title()}({self.post.name.upper()})"


class InspectionDailyLog(models.Model):
    vehicle_choices = [
        ("private", "Private"),
        ("SLG", "SLG"),
    ]
    status_choices = [
        ("fail", "Fail"),
        ("pass", "Pass"),
    ]
    zone_choices = [
        ("north", "North"),
        ("central", "Central"),
        ("east/west", "East/West"),
        ("south", "South"),
        ("special", "Special"),
    ]

    week_choices = [
        ("week1", "Week 1"),
        ("week2", "Week 2"),
        ("week3", "Week 3"),
        ("week4", "Week 4"),
        ("week5", "Week 5"),
    ]
    date = models.DateField()
    zone = models.CharField(max_length=100, choices=zone_choices)
    vehicle = models.CharField(max_length=8, choices=vehicle_choices)
    start = models.TimeField()
    location = models.CharField(max_length=255)
    size = models.CharField(max_length=10)
    job_no = models.CharField(max_length=10)
    appl = models.CharField(max_length=5)
    test_data = models.CharField(max_length=255)
    status = models.CharField(max_length=4, choices=status_choices)
    end = models.TimeField()
    officer = models.ForeignKey(
        Officer,
        on_delete=models.CASCADE,
        related_name="officers",
        null=True,
        blank=True,
    )
    assistant = models.ForeignKey(
        Officer,
        on_delete=models.CASCADE,
        related_name="assistants",
        null=True,
        blank=True,
    )

    def get_absolute_url(self):
        return reverse("inspection-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.job_no}"


class Defect(models.Model):
    sheet_no = models.IntegerField(unique=True, null=True)
    date = models.DateField()
    app_no = models.CharField(max_length=5, verbose_name="application number")
    app_name = models.CharField(max_length=100, verbose_name="applicant's name")
    officer = models.ForeignKey(
        Officer,
        on_delete=models.CASCADE,
        related_name="wiremen",
        verbose_name="wireman/contactor",
        null=True,
        blank=True,
    )
    location = models.CharField(max_length=255)
    insp_date = models.DateField(verbose_name="inspection date")
    defects = models.TextField()
    re_insp_fee = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name="re-inspection fee"
    )
    defect_sheet = models.FileField(upload_to="inspections/defect_sheet/", null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("inspection-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"Application number#{self.app_no}"


class InspectionApplication(models.Model):
    INSTALLATION_TYPE_CHOICES = [
        ("1P", "1Phase"),
        ("3P", "3Phase"),
    ]
    nature_of_work_choices = [
        ("dom", "Domestic"),
        ("com", "Commercial"),
        ("temp", "Temporary"),
        ("rout", "Routine"),
        ("perd", "Periodic"),
    ]
    ZONE_CHOICES = [
        ("north", "North"),
        ("central", "Central"),
        ("east/west", "East/West"),
        ("south", "South"),
        ("special", "Special"),
    ]
    date = models.DateField(blank=True, null=True)
    job_no = models.CharField(max_length=5, verbose_name="application number")
    receipt_no = models.CharField(max_length=10, verbose_name="receipt number")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    cert_no = models.CharField(max_length=10, verbose_name="certificate number")
    name = models.CharField(max_length=100)
    area = models.CharField(max_length=100)
    zone = models.CharField(max_length=10, choices=ZONE_CHOICES, null=True, blank=True)
    contractor = models.ForeignKey(
        Officer,
        on_delete=models.CASCADE,
        related_name="contractors",
        null=True,
        blank=True,
    )
    lights = models.IntegerField(default=0, blank=True, null=True)
    sockets = models.IntegerField(default=0, blank=True, null=True)
    switches = models.IntegerField(default=0, blank=True, null=True)
    inst_type = models.CharField(
        max_length=6,
        choices=INSTALLATION_TYPE_CHOICES,
        null=True,
        blank=True,
        help_text="Installation Phase Type",
    )
    LN = models.FloatField(default=0, blank=True, null=True)
    NE = models.FloatField(default=0, blank=True, null=True)
    LE = models.FloatField(default=0, blank=True, null=True)
    L1_L3 = models.FloatField(default=0, blank=True, null=True)
    L3_L2 = models.FloatField(default=0, blank=True, null=True)
    L1_L2 = models.FloatField(default=0, blank=True, null=True)
    L1_L3_L2_N = models.FloatField(default=0, blank=True, null=True)
    L1_L3_L2_E = models.FloatField(default=0, blank=True, null=True)
    E = models.FloatField(default=0, blank=True, null=True)
    EN = models.FloatField(default=0, blank=True, null=True)
    RE = models.FloatField(default=0, blank=True, null=True)
    kW = models.FloatField(default=0, blank=True, null=True)
    next_inspection = models.DateField(blank=True, null=True)
    CT_RT = models.CharField(max_length=100, blank=True, null=True)
    insp_type = models.CharField(
        max_length=15,
        choices=nature_of_work_choices,
        verbose_name="inspection type",
        blank=True,
        null=True,
    )
    mA = models.IntegerField(default=0, blank=True, null=True)
    sub_circuit = models.IntegerField(default=0, blank=True, null=True)
    main_rating = models.IntegerField(default=0, blank=True, null=True)
    inspector = models.ManyToManyField(
        Officer, related_name="app_inspectors", blank=True
    )
    assistant = models.ManyToManyField(
        Officer, related_name="app_assistants", blank=True
    )
    inspection_date = models.DateField()
    collected_by = models.CharField(max_length=100, blank=True, null=True)
    date_collected = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # owner = models.CharField(max_length=100, blank=True, null=True)
    # owner_address = models.TextField(blank=True, null=True, verbose_name="owner's address")
    # location = models.TextField()
    # nature_of_work = models.CharField(max_length=20, choices=nature_of_work_choices)
    # points = models.IntegerField()
    # contactor_address = models.TextField()
    # contactor_licence_no = models.CharField(
    #     max_length=100, verbose_name="licence number"
    # )
    file = models.FileField(
        upload_to="inspections/applications/", blank=True, null=True
    )

    def get_absolute_url(self):
        return reverse("inspection-application-detail", kwargs={"pk": self.pk})

    def get_total(self):
        return self.lights + self.sockets + self.switches

    def __str__(self):
        return f"Application number#{self.app_no}"

app/inspections/forms.py
from django import forms

from .models import Defect, InspectionApplication, Officer


class OfficerForm(forms.ModelForm):
    class Meta:
        model = Officer
        fields = "__all__"
        # widgets = {
        #     "date_collected": forms.DateInput(attrs={"type": "date"}),
        #     "date": forms.DateInput(attrs={"type": "date"}),
        #     "inspection_date": forms.DateInput(attrs={"type": "date"}),
        # }


class InspectionApplicationForm(forms.ModelForm):
    class Meta:
        model = InspectionApplication
        fields = "__all__"
        widgets = {
            "date_collected": forms.DateInput(attrs={"type": "date"}),
            "date": forms.DateInput(attrs={"type": "date"}),
            "inspection_date": forms.DateInput(attrs={"type": "date"}),
        }


class DefectForm(forms.ModelForm):
    class Meta:
        model = Defect
        fields = "__all__"
        widgets = {
            "date": forms.DateInput(attrs={"type": "date"}),
            "insp_date": forms.DateInput(attrs={"type": "date"}),
        }

app/inspections/views.py
from django.db.models import Q
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import DefectForm, InspectionApplicationForm
from .models import Defect, InspectionApplication, InspectionDailyLog, Officer


class OfficerListView(ListView):
    model = Officer
    ordering = ["-created_at"]

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Officer.objects.filter(
                Q(name__icontains=query)
                | Q(licence_no__icontains=query)
                | Q(email__icontains=query)
                | Q(phone__icontains=query)
                | Q(post__name__icontains=query)
                | Q(office__name__icontains=query)
            ).distinct()
        return super().get_queryset()


class OfficerDetailView(DetailView):
    model = Officer


class OfficerCreateView(CreateView):
    model = Officer
    fields = "__all__"


class OfficerUpdateView(UpdateView):
    model = Officer
    fields = "__all__"


class InspectionApplicationListView(ListView):
    model = InspectionApplication
    ordering = ["-date"]

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return InspectionApplication.objects.filter(
                Q(app_no__icontains=query)
                | Q(receipt_no__icontains=query)
                | Q(cert_no__icontains=query)
                | Q(name__icontains=query)
                | Q(area__icontains=query)
                | Q(contactor__icontains=query)
                | Q(ins_type__icontains=query)
                | Q(collected_by__icontains=query)
                | Q(date_collected__icontains=query)
            ).distinct()
        return super().get_queryset()


class InspectionApplicationDetailView(DetailView):
    model = InspectionApplication


class InspectionApplicationCreateView(CreateView):
    model = InspectionApplication
    form_class = InspectionApplicationForm

    # success url to list view
    def get_success_url(self):
        return reverse("inspection-application-list")


class InspectionApplicationUpdateView(UpdateView):
    model = InspectionApplication
    form_class = InspectionApplicationForm


class InspectionDailyLogListView(ListView):
    model = InspectionDailyLog
    ordering = ["-date"]

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return InspectionDailyLog.objects.filter(
                Q(zone__icontains=query)
                | Q(vehicle__icontains=query)
                | Q(size__name__icontains=query)
                | Q(job_no__icontains=query)
                | Q(appl__icontains=query)
                | Q(test_data__icontains=query)
                | Q(status__icontains=query)
                | Q(inspector__name__icontains=query)
                | Q(assistance__name__icontains=query)
            ).distinct()
        return super().get_queryset()


class InspectionDailyLogDetailView(DetailView):
    model = InspectionDailyLog


class InspectionDailyLogCreateView(CreateView):
    model = InspectionDailyLog
    fields = "__all__"


class InspectionDailyLogUpdateView(UpdateView):
    model = InspectionDailyLog
    fields = "__all__"


class DefectListView(ListView):
    model = Defect
    ordering = ["-date"]

    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Defect.objects.filter(
                Q(sheet_no__icontains=query)
                | Q(app_no__icontains=query)
                | Q(inspector__name__icontains=query)
                | Q(location__icontains=query)
                | Q(defects__icontains=query)
                | Q(re_insp_fee__icontains=query)
            ).distinct()
        return super().get_queryset()


class DefectDetailView(DetailView):
    model = Defect


class DefectCreateView(CreateView):
    model = Defect
    form_class = DefectForm


class DefectUpdateView(UpdateView):
    model = Defect
    form_class = DefectForm

app/templates/inspections/inspection_detail.html
{% extends 'base.html' %}

{% load inspections_extras %}

{% block content %}
<div class="col-lg-6 mx-auto">
    <div class="text-center">
        <h1>Electrical Installation Inspection Report</h1>
        <p class="fw-bold fs-5">(Defect sheets to be served on consumers)</p>
    </div>
    <p class="text-end text-danger"><strong>No: </strong>{{object.sheet_no}}
    </p>
    <p><strong>Date: </strong>{{object.date}}</p>
    <p><strong>Application No: </strong>{{object.app_no}}</p>
    <p><strong>Applicant's Name: </strong>{{object.app_name}}</p>
    <p><strong>Wireman/Contractor's Name & No: </strong>{{object.inspector}}
    </p>
    <p>An inspection and testing of the installtion on your premises at
        <strong>{{object.location}}</strong> was carried out on
        <strong>{{object.insp_date}}</strong>
    </p>
    <p><strong>The following defects were observed:</strong></p>
    <p>{{object.defects|mark_down}}</p>
    <p><strong>You are advised to remedy the said defects immediately, failing which as
        approval certificate will not be issued/a disconnection of supply to
        your installation will be ordered *</strong></p>
    <p><strong>(*delete whichever is not applicable)</strong></p>
    <p><strong>Re-inspection Fee:</strong>${{object.re_insp_fee}}</p>

    <div class="text-end">
        <a class="btn btn-dark px-5 rounded4"
            href="{% url 'inspection-update' object.pk %}">Edit</a>
    </div>
</div>
{% endblock %}

app/templates/inspections/inspection_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>{% if form.instance.pk %}Update
        {% else %}Add
        {% endif %}</h1>
    <hr>
    <form class="col-lg-4 mx-auto"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class="text-end">
            <button type="submit"
                class="btn btn-dark px-5 rounded-4">Save</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/inspections/inspection_list.html
{% extends 'base.html' %}

{% block content %}
<form class="col-lg-4 mx-auto"
    method="get">
    <input class="rounded-4 form-control"
        type="text"
        name="q"
        placeholder="Search..."
        value="{{ request.GET.q }}">
    <br>
    <div class="text-end">
        <button class="btn btn-dark px-5 rounded-4"
            type="submit">Search</button>
    </div>
</form>
<hr>
<a class="btn btn-dark px-5 rounde-4"
    href="{% url 'inspection-create' %}">Add</a>
<br><br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Application number</th>
            <th scope="col">Applicant</th>
            <th scope="col">Inspector</th>
            <th scope="col">Location</th>
            <th scope="col">Inspection date</th>
            <th scope="col">Re-inspection fee</th>
        </tr>
    </thead>
    <tbody>
        {% for object in object_list %}
        <tr>
            <th scope="row">1</th>
            <td>
                <a class="text-dark"
                    href="{{object.get_absolute_url}}">#{{ object.app_no }}</a>
            </td>
            <td>{{object.app_name}}</td>
            <td>{{object.inspector}}</td>
            <td>{{object.location}}</td>
            <td>{{object.insp_date}}</td>
            <td>${{object.re_insp_fee}}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="7"
                class="text-center">Empty</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/inspections/inspectionapplication_detail.html
{% extends 'base.html' %}

{% load inspections_extras %}

{% block content %}
<div class="col-lg-6 mx-auto">
    <div class="text-center">
        <h1>Electrical Installation Inspection Report</h1>
        <p class="fw-bold fs-5">(Defect sheets to be served on consumers)</p>
    </div>
    <p class="text-end text-danger"><strong>No: </strong>{{object.sheet_no}}
    </p>
    <p><strong>Date: </strong>{{object.date}}</p>
    <p><strong>Application No: </strong>{{object.app_no}}</p>
    <p><strong>Applicant's Name: </strong>{{object.app_name}}</p>
    <p><strong>Wireman/Contractor's Name & No: </strong>{{object.inspector}}
    </p>
    <p>An inspection and testing of the installtion on your premises at
        <strong>{{object.location}}</strong> was carried out on
        <strong>{{object.insp_date}}</strong>
    </p>
    <p><strong>The following defects were observed:</strong></p>
    <p>{{object.defects|mark_down}}</p>
    <p><strong>You are advised to remedy the said defects immediately, failing which as
        approval certificate will not be issued/a disconnection of supply to
        your installation will be ordered *</strong></p>
    <p><strong>(*delete whichever is not applicable)</strong></p>
    <p><strong>Re-inspection Fee:</strong>${{object.re_insp_fee}}</p>

    <div class="text-end">
        <a class="btn btn-dark px-5 rounded4"
            href="{% url 'inspection-application-update' object.pk %}">Edit</a>
    </div>
</div>
{% endblock %}

app/templates/inspections/inspectionapplication_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="col-lg-4 mx-auto p-5 my-5">
    <h1 class="h3 mb-3 font-weight-normal">Inspection Application</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="text-end">
            <button class="btn btn-dark"
                type="submit">Submit</button>
        </div>
    </form>
</div>
<script>
    $("#id_inspector").select2();
    $("#id_assistant").select2();
    $("#id_contractor").select2();
</script>
{% endblock content %}

app/templates/inspections/inspectionapplication_list.html
{% extends 'base.html' %}

{% block content %}
<form class="col-lg-4 mx-auto"
    method="get">
    <input class="rounded-4 form-control"
        type="text"
        name="q"
        placeholder="Search..."
        value="{{ request.GET.q }}">
</form>
<br>
<a class="btn btn-dark px-5 rounded-4"
    href="{% url 'inspection-application-create' %}">Add</a>
<br><br>
<div class="table-responsive">
    <table class="table table-hover table-sm small">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Date</th>
                <th scope="col">Application</th>
                <th scope="col">Receipt(Amt)</th>
                <th scope="col">Cert</th>
                <th scope="col">Name</th>
                <th scope="col">Area(Zone)</th>
                <th scope="col">Contactor</th>
                <th scope="col">LT</th>
                <th scope="col">SKT</th>
                <th scope="col">SW</th>
                <th scope="col">PTS</th>
                <th scope="col">LE</th>
                <th scope="col">LN</th>
                <th scope="col">EN</th>
                <th scope="col">TYP</th>
                <th scope="col">mA</th>
                <th scope="col">S-CKTs</th>
                <th scope="col">MN RT</th>
                <th scope="col">INSP/ASST</th>
                <th scope="col">Inspection date</th>
                <th scope="col">Collected</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">1</th>
                <td>{{object.date}}</td>
                <td>
                    <a class="text-dark"
                        href="{{object.get_absolute_url}}">
                        #{{ object.app_no }}</a>
                </td>
                <td>{{object.receipt_no}}(${{object.amount}})</td>
                <td>{{object.cert_no}}</td>
                <td>{{object.name}}</td>
                <td>{{object.area}}({{object.zone}})</td>
                <td>{{object.contactor}}</td>
                <td>{{object.lights}}</td>
                <td>{{object.sockets}}</td>
                <td>{{object.switches}}</td>
                <td>{{object.get_total}}</td>
                <td>{{object.BC}}</td>
                <td>{{object.LE}}</td>
                <td>{{object.LN}}</td>
                <td>{{object.EN}}</td>
                <td>{{object.AE}}</td>
                <td>{{object.ins_type|truncatechars:4|upper}}</td>
                <td>{{object.mA}}mA</td>
                <td>{{object.sub_circuit}}</td>
                <td>{{object.main_rating}}A</td>
                <td>
                    {% for inspector in object.inspector.all %}
                    <a href="">{{inspector.name|title}}</a>,
                    {% endfor %}
                    /
                    {% for assistant in object.assistant.all %}
                    <a href="">{{assistant.name|title}}</a>,
                    {% endfor %}
                </td>
                <td>{{object.inspection_date}}</td>
                <td>{{object.collected_by}}({{object.date_collected}})</td>

            </tr>
            {% empty %}
            <tr>
                <td colspan="24"
                    class="text-center fw-bold">Nothing</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/inspections/inspector_detail.html
{% extends 'base.html' %}

{% load inspections_extras %}

{% block content %}
<div class="col-lg-6 mx-auto">
    <div class="row">
        <h2>{{object.name|title}} #{{object.licence_no}}</h2>
        <hr>
        <div class="col">
            <p><strong>Post: </strong>{{object.post}}</p>
            <p><strong>Office: </strong>{{object.office}}</p>

        </div>
        <div class="col">
            <p><strong>Email: </strong>{{object.email}}</p>
            <p><strong>Phone: </strong>{{object.phone}}</p>
        </div>
        <div class="text-end">
            <a class="btn btn-dark" href="{% url 'inspector-update' object.pk %}">Edit</a>
        </div>
    </div>
    <hr>
    <div class="row">
        <p>Notes: {{object.notes}}</p>
    </div>
</div>
{% endblock %}

app/templates/inspections/inspector_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>{% if form.instance.pk %}Update
        {% else %}Add
        {% endif %}</h1>
    <hr>
    <form class="col-lg-4 mx-auto"
        method="post"
        enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class="text-end">
            <button type="submit"
                class="btn btn-dark px-5 rounded-4">Save</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/inspections/inspector_list.html
{% extends 'base.html' %}

{% block content %}
<form class="col-lg-4 mx-auto"
    method="get">
    <input class="rounded-4 form-control"
        type="text"
        name="q"
        placeholder="Search..."
        value="{{ request.GET.q }}">
</form>
<br>
<a class="btn btn-dark px-5 rounded-4"
    href="{% url 'inspection-application-create' %}">Add</a>
<br><br>
<div class="table-responsive col-lg-4 mx-auto">
    <table class="table table-hover table-sm small">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Phone</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>
                    <a class="text-dark"
                        href="{{object.get_absolute_url}}">
                        {{ object.name|title }} #{{object.licence_no}}</a>
                </td>
                <td>{{object.phone}}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="24"
                    class="text-center fw-bold">Nothing</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}